# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-28 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20160428_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='upload',
            field=models.FileField(upload_to='/home/darknight/Desktop/Django-First-Try-master/srcmedia/'),
        ),
    ]
