# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-29 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_auto_20160428_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('course_id', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='resource',
            name='upload',
            field=models.FileField(upload_to='/home/darknight/Desktop/studyiit/src/media/'),
        ),
    ]
