# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-29 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_auto_20160429_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
