# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-29 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_auto_20160429_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='course_id',
            new_name='course_name',
        ),
    ]
