# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-30 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_auto_20160429_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('L', 'Lectures'), ('Q', 'Quizzes'), ('T', 'Tutorials'), ('M', 'Midsem and Endsem')], default='L', max_length=30),
        ),
    ]
